### ISSUE TITLE
AppVeyor job won't run if the last committer was Chocolatey

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-packages-template#5]
This is something @majkinetor noted - https://github.com/majkinetor/chocolatey/issues/21

It's similar here. We want the job to run each time, so perhaps just look at the last job run time and if it was a few minutes before, we halt it.

**Comment by ferventcoder** [comment]
Asking for a potential solution - https://twitter.com/ferventcoder/status/770298610160312320

**Comment by ferventcoder** [comment]
The solution is to write the commit with the message `[skip-ci]` - it will still build during cron schedule - https://twitter.com/appveyor/status/770299894175182849

**Comment by ferventcoder** [comment]
cc @danstis @mikecole @aronovgj - you may want to incorporate this one so that everything works appropriately

**Comment by majkinetor** [comment]
Yeah, I know about skip_ci but that is AV specific. If you use another build server it wont work, so I think both solutions should be in place.

**Comment by ferventcoder** [comment]
@majkinetor if you use another build server though, you'd make that change probably in its interface, not in appveyor.yml. ;)
