### ISSUE TITLE
Make the user email secure in appveyor.yml

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-packages-template#6]
@danstis did this, and it's a great idea.

**Comment by ferventcoder** [comment]
Done

**Comment by danstis** [comment]
Haha, yeah I didn't like the idea of spam robots finding my email... Unfortunately I didn't know the Appveyor format well enough to also abstract the email on the git email on line 41.

**Comment by ferventcoder** [comment]
@danstis https://github.com/chocolatey/chocolatey-packages-template/blob/6ad362f8c8f300b1335fc9e8725f5dbcedf28e0f/appveyor.yml#L69 should be most helpful in that regard.
